export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const ON_LOGOUT = "ON_LOGOUT";

export const FETCH_TODO_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_COMPLETED_SUCCESS = 'FETCH_COMPLETED'

export const ADD_TODO = "ADD_TODO";

export const UPDATE_TODO = 'UPDATE_TODO'
export const UPDATE_COMPLETED = 'UPDATE_COMPLETED'

export const DELETE_TODO = 'DELETE_TODO'
export const DELETE_COMPLETED = 'DELETE_COMPLETED'


